name: Build and Deploy .NET Core API to Azure App Service (Container)

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Login to ACR using Azure CLI
        run: az acr login --name ${{ secrets.ACR_NAME }}
      
      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}


      - name: Build and push Docker image to ACR
        run: |
          docker build -t $ACR_URL/api:latest ./VSRAdminAPI
          docker push $ACR_URL/api:latest
        env:
          ACR_URL: ${{ secrets.ACR_NAME }}.azurecr.io

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.API_APP_NAME }}
          images: ${{ secrets.ACR_NAME }}.azurecr.io/api:latest
