name: Build and Deploy .NET Core API to Azure App Service (Container)

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Login to Azure Container Registry (ACR)
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and push Docker image to ACR
        run: |
          docker build -t $ACR_URL/api:latest ./VSRAdminAPI
          docker push $ACR_URL/api:latest
        env:
          ACR_URL: ${{ secrets.ACR_NAME }}.azurecr.io

      - name: Update Azure Web App to use new Docker image
        run: |
          az webapp config container set \
            --name ${{ secrets.API_APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --docker-custom-image-name ${{ secrets.ACR_NAME }}.azurecr.io/api:latest \
            --docker-registry-server-url https://${{ secrets.ACR_NAME }}.azurecr.io \
            --docker-registry-server-user ${{ secrets.ACR_USERNAME }} \
            --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}
