name: Build and Deploy .NET Core API to Azure App Service (Container)

on:
  push:
    branches:
      - main

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  AZURE_CONTAINER_REGISTRY: ${{ secrets.ACR_NAME }}.azurecr.io
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  API_APP_NAME: ${{ secrets.API_APP_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI - Login to ACR
      run: |
        az acr login --name $ACR_NAME

    - name: Build and push Docker image to ACR
      run: |
        docker build -t $AZURE_CONTAINER_REGISTRY/api:latest ./VSRAdminAPI
        docker push $AZURE_CONTAINER_REGISTRY/api:latest

    - name: Deploy image to Azure App Service (Container)
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.API_APP_NAME }}
        images: ${{ env.AZURE_CONTAINER_REGISTRY }}/api:latest

    - name: Wait for app to become available and test root endpoint (optional)
      run: |
        echo "Waiting for deployment to propagate..."
        sleep 30
        curl -v https://${{ env.API_APP_NAME }}.azurewebsites.net/
